<?php

namespace AppBundle\Repository;

/**
 * CompositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompositionRepository extends \Doctrine\ORM\EntityRepository
{
}
