<?php

namespace AppBundle\Repository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends \Doctrine\ORM\EntityRepository
{
//
//    public function getTest()
//    {

        // Je veut selectionnez tous les ingrédients présents dans le mois en cours

//        $m = date('m') - 1;
//        $qb = $this->createQueryBuilder('i')
//            ->
//            ->innerJoin('p.recette r')
//            ->where('')
//            ->where('p.mois = :month')
//            ->setParameter('month', $m)
//            ->getQuery()
//        ;
//        return $qb->getResult();
//    }

}
