<?php

namespace AppBundle\Repository;

use AppBundle\Entity;

/**
 * MoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoisRepository extends \Doctrine\ORM\EntityRepository
{

    public function getActualMonth($user)
    {
        $actualMonth = date('m') - 1;
        $actualYear = date('Y');
        $qb = $this->createQueryBuilder('m')
            ->where('m.monthNumber = :month')
            ->andWhere('m.year = :year')
            ->join('m.plannings', 'p')
            ->andWhere('p.user = :user')
            ->setParameter('month', $actualMonth)
            ->setParameter('year', $actualYear)
            ->setParameter('user', $user)
	        ->getQuery();

        return $qb->getResult();
    }

    public function getNextMonth($user)
    {
        $nextMonth = date('m');
        $actualYear = date('Y');
        $qb = $this->createQueryBuilder('m')
            ->where('m.monthNumber = :month')
            ->andWhere('m.year = :year')
            ->join('m.plannings', 'p')
            ->andWhere('p.user = :user')
            ->setParameter('month', $nextMonth)
            ->setParameter('year', $actualYear)
            ->setParameter('user', $user)
            ->getQuery();

        return $qb->getResult();
    }

    public function getListeCourses($id)
    {
    	$req = $this->getEntityManager()->createQuery(
    		'SELECT i.nom ingredient, u.symbole unite, SUM(comp.quantite) quantite
    		      FROM AppBundle:Mois m
				  JOIN m.plannings p
				  JOIN p.recette r
				  JOIN r.compositions comp
				  JOIN comp.ingredient i
				  JOIN i.unite u
				  WHERE m.id = :month
				  GROUP BY ingredient, unite'
	    )->setParameter('month', $id);


    	return $req->getResult();
    }

    public function getMonthByUser($user)
    {
        $req = $this->createQueryBuilder('m')
            ->where('m.user = :user')
            ->setParameter('user', $user)
            ->getQuery();

        return $req->getResult();
    }

}
