<?php

namespace AppBundle\Repository;

/**
 * PlanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningRepository extends \Doctrine\ORM\EntityRepository
{

    public function getMonthById($id)
    {
        $qb = $this->createQueryBuilder('p')
            ->where('p.mois = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $qb->getResult();
    }


}
