imports:
    - { resource: config.yml }

doctrine:
    dbal:
        driver: pdo_mysql
        host: '%CLEARDB_DATABASE_URL%'
        port: '%database_port%'
        dbname: '%DB_NAME%'
        user: '%DB_USER%'
        password: '%DB_PASS%'
        charset: UTF8
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: "php://stderr"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
